.travis.yml
Running the same tests on the branch and PR pipeline is a waste :)
compare with https://github.com/semi-technologies/weaviate-chaos-engineering/pull/7/checks
=> Only run chaos tests with branch pipeline

.travis.yml, apps/chaotic-killer/Dockerfile, apps/chaotic-killer/run.sh, apps/compare-rest-graphql/Dockerfile, apps/compare-rest-graphql/objects-are-not-deleted.py, apps/compare-rest-graphql/requirements.txt, compare_rest_graphql_while_crashing.sh
Added new test `compare_rest_graphql_while_crashing.sh`
It tries to generate discrepancies between REST and GraphQL by continually overwriting data and crashing Weaviate.
The `chaotic-killer` docker container was modified to use docker kill rather than kill inside the container. The reason for this was that restarts were being affected by a backoff policy when killing frequently inside the container that made things slower (perhaps part of the tini process supervisor run as part of docker).
=> Compare REST vs GraphQL

.travis.yml, apps/backup_and_restore_crud/Dockerfile, apps/backup_and_restore_crud/backup_and_restore_crud.py, apps/backup_and_restore_version_compatibility/backup_and_restore_version_compatibility.py, apps/weaviate/docker-compose-backup.yml, backup_and_restore_multi_node_crud.sh, backup_and_restore_version_compatibility.sh
Uses the existing `backup_and_restore_crud` app to run the CRUD chaos tests on a multi-node setup. Currently the single node `backup_and_restore_crud` test remains, but we can probably remove it in the future once there is no doubt that multi-node and singe-node backup/restore behaviors are in parity. Under the hood there is not a distinction between single and multi node backups, but "better safe than sorry" for now.
Also, the GCS emulator has been removed in favor of Minio/S3. This is because:
- The GCS emulator is buggy when object counts exceed a trivial amount. It starts returning 404s when the number of backed up objects approaches 1,000. The test introduced in this PR generates 100,000 objects.
- The GCS emulator is neither an official Google image, nor is it maintained by a well …
=> Multi-node backup/restore CRUD chaos test

.github/workflows/tests.yaml, ann_benchmark.sh, ann_benchmark_aws.sh, ann_benchmark_compression.sh, ann_benchmark_compression_aws.sh, ann_benchmark_compression_gcp.sh, ann_benchmark_gcp.sh, apps/ann-benchmarks/analyze.py
This adds two more AWS-builds that run with `glove-100-angular`?
Angular distance requires normalization, we had a bug that destroyed recall for angular datasets, but couldn't catch it with the pipeline because it only used a euclidean-based dataset
GCP is slower and the performance is unpredictable. It's questionable if we get any value out of the GCP pipelines in the current form. AWS is very stable and only has minimal fluctuation between runs.
1. It's prominently featured in the official `ann-benchmarks` repo
2. It is large enough to be challenging, yet small enough to complete in the time that the longest existing chaos pipeline takes, so the total runtime won't be any longer because of this dataset.
=> Run `glove-100-angular` on AWS - both compressed and uncompressed

apps/ann-benchmarks/weaviate_query.py
`i` will be `len(vectors) - 1` so leads to incorrect recall calculation.
=> Fix recall calculation

.github/workflows/tests.yaml, apps/multi-node-references/Dockerfile, apps/multi-node-references/requirements.txt, apps/multi-node-references/run.py, multi_node_ref_imports.sh
For context see:
* https://github.com/weaviate/weaviate/issues/3179
* https://github.com/weaviate/weaviate/pull/3180
New Pipeline:
* Import batches (containing many refs) into a 3-node cluster, all classes are shared across nodes, so network requests are inevitable for ref validation
* The pipeline fails if any batch insert has an error 
* Old versions would fail for example after a node has been pronounced dead with something like "can't resolve hostname"
* Even if the imports pass, the pipeline would fail if there is a single `memberlist` log with level `error`
* With the old version we see 10s or 100s of those
=> Add new pipeline for ref-imports in multi-node setting

.github/workflows/tests.yaml, apps/ann-benchmarks/requirements.txt
This PR bumps the `weaviate-client[grpc]` dependency in `apps/ann-benchmarks` to use the new Python client pre-release tag that includes the recent breaking gRPC changes
=> Bump `weaviate-client[grpc]` from `v3.22.0b0` to `v3.25.0b0`

.github/workflows/matrix.yaml, .github/workflows/tests.yaml, README.md, apps/multi-tenancy-concurrent-imports/docker-compose-importers.yml
We see a lot of flaky timeout due to (we assume) resource starving. Add a concurrency limit to see if it helps with the flakyness due to resources constraints/starving.
Fixes:
* add IMPLICIT_TENANT_RATIO to env to avoid multi import pipeline fialing
* add timeouts to jobs to catch long running/stuck jobs earlier
* add concurrency limit on the matrix to avoid starving runners and triggering exhaustion failures
* use paid GHA runners instead of free runners
=> Adjustment to chaos pipeline to improve stability

.github/workflows/tests.yaml, apps/ann-benchmarks/requirements.txt, apps/ann-benchmarks/weaviate_import.py, apps/ann-benchmarks/weaviate_query.py, apps/rest-patch-stops-working-after-restart/rest-patch-stops-working-after-restart.py
This PR adapts the ann-benchmark code to support the latest changes from the Weaviate's Python client version 4.
All changes were tested with the most recent version, weaviate-client-4.4b9.dev254+g14ba0392, besides the version 4.4.rc0. So, it working with the GA version of the python client which will be released in couple of days.
=> Add support for latest Weaviate Python client version 4.0 GA.

.github/workflows/tests.yaml, apps/backup_and_restore_version_compatibility/backup_and_restore_version_compatibility.py, apps/backup_and_restore_version_compatibility/generate_version_pairs.py
After an incident raised by our SREs in which they couldn't restore a backup obtained when the cluster was in 1.22.5 into a newly created backup in 1.24.0 I decided to dig into the backup_and_restore_version_compatibility pipeline and found out that the issue was also occurring, but it was not caught by the job because the verification logic didn't take into consideration the case in which the query returns an empty list.
This PR fixes the pipeline by comparing the number of items from source node and destination node, as well as the content for each item retrieved in the query. 
Also, it updates the WEAVIATE_VERSION to 1.24.3, which includes the fix for this issue.
=> Fix backup and restore version compatibility data verification

.github/workflows/tests.yaml, apps/backup_and_restore_out_of_sync/Dockerfile, apps/backup_and_restore_out_of_sync/backup_and_restore_out_of_sync.py, apps/backup_and_restore_out_of_sync/requirements.txt, backup_and_restore_multi_node_out_of_sync.sh
This new pipeline creates a set of 100 classes in a 2-node cluster. Performs a backup, deletes the schema and restores the backup. The issue was that when restoring the data the second node was out of sync with the first one. This issue got fixed in 1.24.6, so bumping the WEAVIATE_VERSION too.
=> Add chaos-pipeline to verify and catch schema out-of-sync after backup restore

apps/upgrade-journey/containers.go, apps/upgrade-journey/versions.go
fix configuration for `RAFT_JOIN` for rolling update in singlre nodes test
=> fix: rolling update in single nodes test

.github/workflows/tests.yaml, apps/multi-node-references/requirements.txt, apps/multi-node-references/run.py, apps/upgrade-journey/containers.go, apps/upgrade-journey/run.go, replication_tunable_consistency.sh
Add a polling mechanism to have the upgrade test proceed once graphQL has the schema realoaded (graphql fix)
Add a polling mechanism to have large cluster import proceed once the class is present in the schema (EC fix)
Fix nil pointer lookup in upgrade journey test
Make tunable replication consistency test dump logs when failing
=> Stabilize test failing due to graphQL ready delay

.github/workflows/matrix.yaml
This commit adds a new cron trigger for the chaos-pipeline, so that it will run on every day basis.
If the trigger is the cron one, then the weaviate version used is latest, otherwise whatever value passed in input.weaviate_version or the default.
After running, a slack message will be sent to a webhook to notify about the failures.
=> Add periodic chaos-pipeline run.

.github/workflows/matrix.yaml
Also, updates the chaos-pipeline into using 1.25.2 version instead.
=> Run Send Slack message even if previous task fails.

.github/workflows/matrix.yaml
When using the slack-github-action, we need to pass the channel in a hex format, not as a string, otherwise the request fails. Also, hyperlinks aren't supported by slack workflows, therefore only the link can be sent as part of the message and adds the weavite-version-information job in needs, so it gets access to its context.
=> Pass the slack channel in the right format.

apps/ann-benchmarks/requirements.txt
Most of the ann-benchmark tests are failing with:
numpy.dtype size changed, may indicate binary incompatibility. Using numpy version older than 1.20.0 fixes the problem
=> Fix numpy version incompatibility with h5py.

.github/workflows/matrix.yaml
we have now 
- custom runs from the UI
- runs on push on an open PR 
- cron runners 
this PR disable running on merging to main branches `main` and `pipeline/*` in order to save costs given that the PR will be ran before merging
=> cost: ignore running pipeline on main branches after merge

.github/workflows/matrix.yaml
we have now 
- running via the GH UI workflow dispatcher 
- cron '0 0 */2 * *'
to save time and cost will disable the automatic runs  on pushing to branches
=> disable running pipeline on pushs to save costs and time

.github/workflows/matrix.yaml, .github/workflows/tests.yaml
This PR enhances the flexibility and precision of our CI pipeline for tagged releases by:
1.	Determining the Real Semver Version of Weaviate Under a Tag:
•	Removes the weaviate_max_major_version_test_set parameter.
•	Introduces a chain of jobs that leverage the weaviate-version-in-image composite action to retrieve the actual semantic version of Weaviate under a given tag.
•	Based on this real version, the pipeline dynamically checks if a specific job should run, ensuring compatibility with the required minimum version.
2.	Allowing the Execution of a Specific Chaos Test:
•	Adds a new parameter, test_to_run, that allows specifying a single chaos test to run.
•	If no value is provided, the pipeline will default to executing all chaos tests.
=> Improve chaos triggers

ann_benchmark_aws.sh
It was noted that some of the AWS instances didn't cleanup properly, incurring in extra costs from our AWS EC2 account. This commit makes sure that the instance gets deleted and if for whatever reason it didn't after 5 minutes, the job will fail. So that the person monitoring the job can take a look at the AWS' instances or escalate the issue to SRE.
=> Make the ann-benchmark AWS instance deletion resilient.

ann_benchmark_gcp.sh, ann_benchmark_quantization_aws.sh, ann_benchmark_quantization_gcp.sh
We are getting recently errors that the SSH key didn't have
time enought to propage. This PR adds a busy loop to wait for SSH to be ready.
Also, it was missed to add cleanup for AWS in the quantization script variant.
=> Add busy loop to wait for instance to be ssh'able

apps/backup-and-flush/requirements.txt, apps/backup_and_restore_crud/requirements.txt, apps/backup_and_restore_out_of_sync/requirements.txt, apps/backup_and_restore_version_compatibility/requirements.txt, apps/compaction-roaringset/requirements.txt, apps/consecutive_create_and_update_operations/requirements.txt, apps/delete_and_recreate/requirements.txt, apps/filter-memory-leak/requirements.txt, apps/geo-crash/requirements.txt, apps/multi-node-references/requirements.txt, apps/recall/requirements.txt, apps/replicated-import/requirements.txt, apps/replicated_import_with_backup/requirements.txt, apps/rest-patch-stops-working-after-restart/requirements.txt, apps/segfault-on-batch-ref/requirements.txt, apps/segfault-on-filtered-vector-search/requirements.txt
The Python v3 client has been deprecated in recent versions and we get now the following error if still using it with the latest versions Upgrade your code to use Python client v4  connections and methods.
- For Python Client v4 usage, see: https://weaviate.io/developers/weaviate/client-libraries/python
- For code migration, see: https://weaviate.io/developers/weaviate/client-libraries/python/v3_v4_migration
If you have to use v3 code, install the v3 client and pin the v3 dependency in your requirements file:
client = weaviate.Client(host, timeout_config=int(30))
=> Pin the weaviate-python-client version for tests using v3.

.github/workflows/matrix.yaml
The periodic chaos engineering job will now use the new nightly tag which points to the very last content in main.
=> Update from latest to nightly.

async_repair.sh
In a recent change, the async replication time at which the repairing occurs has been modified and added a new environemtn variable which allows its configuration. The default value is 30 seconds, therefore we need to wait a little longer.
=> Increase the delay to wait for async replication.

.github/workflows/tests.yaml, apps/upgrade-journey-object-nested-properties/docker-compose-single.yml, upgrade_journey_object_nested_properties.sh
The upgrade journey nested properties job has been seen failing during [chaos-pieline](https://github.com/weaviate/weaviate-chaos-engineering/actions/runs/13742671744/job/38433745323) execution:
```
Upgrade journey test: single
Start Weaviate v1.25.24
weaviate Pulling 
weaviate Error toomanyrequests: You have reached your unauthenticated pull rate limit. https://www.docker.com/increase-rate-limit
Error response from daemon: toomanyrequests: You have reached your unauthenticated pull rate limit. https://www.docker.com/increase-rate-limit
Error: Process completed with exit code 18.
```
Being the reason that the docker-compose file was pointing at Scarf's proxy registry. This PR removes that reference and uses directly Dockerhub's registry.
Also, as part of this PR, we are updating the …
=> Remove Scarf's proxy reference.

.github/workflows/tests.yaml
As the input to the chaos pipeline are mainly tags, if a tag as nightly gets passed to the get-previous-version then it won't be able to retrieve the latest version, as it's not in SemVer format.
We need to retrieve the real SemVer version first, using the real-version-in-tag action.
=> Use real version in tag for get-previous-version.

.github/workflows/tests.yaml
The if condition to run the test was not correct and the test was being executed for all Weaviate versions.
Fix it to be executed only in Weaviate >= 1.31
=> Muvera: fix version check to run Muvera test

.github/workflows/matrix.yaml, .github/workflows/tests.yaml, ann_benchmark_aws.sh, ann_benchmark_gcp.sh, ann_benchmark_quantization_aws.sh, ann_benchmark_quantization_gcp.sh, cleanup_aws_resources.sh, cleanup_cancelled_aws_resources.sh, cleanup_cancelled_gcp_instances.sh, cleanup_gcp_resources.sh
In some circumstances, the CI jobs don't finish gracefully and that may leave ANN VM running because they weren't clean up automatically.
This PR brings some improvements in that regard:
- Create cleanup script files to be shared across jobs/steps
- Run cleanup steps at the end of every ANN benchmark job, no matter the result
- Additionally, add a final job in the overall pipeline to delete instances
- Now, instances have a name related to the Job ID, to facilitate tracking and cleanup
- Set max up time of 4 hours
- Make both things for AWS and GCP
=> Clean ANN resources in CI

apps/upgrade-journey/containers.go
When running the upgrade-journey job, the time required to wait for the containers needs to be higher when it's running with multiple nodes, as when it runs with a single one.
=> Increase container waiting times for multi-node.

.github/workflows/tests.yaml, apps/ann-benchmarks/analyze.py, apps/ann-benchmarks/requirements.txt, apps/ann-benchmarks/weaviate_import.py
This commit introduces Rotational Quantization (RQ) testing support across the ANN benchmarks suite.
- ann-benchmarks-rq-glove-aws - AWS Glove100 RQ benchmark testing
- ann-benchmarks-rq-sift-gcp - GCP SIFT1M RQ benchmark testing
- Renamed ann-benchmarks-multivector-bq-gcp → ann-benchmarks-multivector-rq-gcp
- Added RQ test step to MUVERA dataset benchmarks
- weaviate_import.py
- Implemented RQ-specific vector index configuration for both single and multivector scenarios
requirements.txt
- Updated weaviate-client to specific commit hash to use temporarily RQ client
=> Add RQ test cases

.github/workflows/matrix.yaml
This PR is part of a bigger effort to centralize the CI triggering and collection of results.
It adds a final job that will update the results of the test execution in a project board. It adds the pass/failed and the link to the job.
=> ci: Automated update of results

apps/weaviate/docker-compose-replication_single_low_network_pressure.yml, replication_tunable_consistency.sh
this config shall make sure flakey tests to be stable to address network overhead caused by memberlist/raft communications given that we are bounded by the runner size
chaos run https://github.com/weaviate/weaviate-chaos-engineering/actions/runs/17862493868
=> pass memberlist fast failure detection and control raft multipler

replication_tunable_consistency.sh
this was causing instability on the replication tunable consistency given that we use volumes now 
run : https://github.com/weaviate/weaviate-chaos-engineering/actions/runs/18316466110/job/52157951141
=> revert: remove the --no-recreate from replication tunable consistency
